# Generated by Django 4.2.3 on 2023-07-09 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0002_rename_categoru_women_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="women",
            old_name="title",
            new_name="name",
        ),
    ]
